[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
url = "2.4.0"
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17"
